fix(grub-mkrescue.c): use upper-case EFI paths
deepin-community/grub2 pull request #11
Opened 2024-06-13 11:41 UTC by MingcongBai

- This is needed to generate bootable ISOs on Loongson firmware. 
    - /efi/boot/bootloongarch64.efi => /EFI/BOOT/BOOTLOONGARCH64.EFI.
- This shouldn't cause problems with other architectures, AFAIK.

Ref: https://lists.gnu.org/archive/html/grub-devel/2024-06/msg00101.html

2024-06-13 11:42 UTC, MingcongBai commented
/integrate

2024-06-21 05:40 UTC, UTsweetyfish requested changes

2024-06-21 05:40 UTC, UTsweetyfish commented on debian/changelog
> +grub2 (2.12-1deepin6deepin1) unstable; urgency=medium
wtf are you doing

2024-06-21 05:42 UTC, MingcongBai commented on debian/changelog
> +grub2 (2.12-1deepin6deepin1) unstable; urgency=medium
Might be helpful to review sooner.

2024-06-21 05:42 UTC, MingcongBai commented
/integrate

2024-06-21 05:43 UTC, Zeno-sole commented
/integrate

2024-06-21 05:43 UTC, UTsweetyfish approved these changes

2024-06-21 05:47 UTC, merged